apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fintrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 692101471621.dkr.ecr.us-east-1.amazonaws.com/fintrack-user-service:01f49c027d224fce2126fc826fc0b8f824a8dea6
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: CONFIG_SERVER_USER
              value: "configadmin"
            - name: CONFIG_SERVER_PASSWORD
              value: "configpass"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://fintrack-mysql.cg9qg6s0qtxb.us-east-1.rds.amazonaws.com:3306/fintrack_users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "fintrack_admin"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintrack-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fintrack-secrets
                  key: jwt-secret
            - name: ACTUATOR_USER
              value: "actuator"
            - name: ACTUATOR_PASSWORD
              value: "changeme"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "256m"
              memory: "768Mi"
            limits:
              cpu: "512m"
              memory: "1.5Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 5
