spring:
  application:
    name: config-server
  profiles:
    active: native
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  security:
    user:
      name: ${CONFIG_SERVER_USER:configadmin}
      password: ${CONFIG_SERVER_PASSWORD:configpass}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true