apiVersion: v1
kind: ConfigMap
metadata:
  name: fintrack-config
  namespace: fintrack
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka"
  CONFIG_SERVER_URL: "http://config-server:8888"
  AWS_REGION: "us-east-1"
  DB_HOST: "fintrack-mysql.cg9qg6s0qtxb.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
