apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: fintrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: 692101471621.dkr.ecr.us-east-1.amazonaws.com/fintrack-config-server:23252e15e260db78d01f61f4459685c59898e66f
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: fintrack
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
